#! /bin/bash

set -e

start() {
    if is_running; then
        echo 'Error: NAV daemon is still running!'
        exit 1
    fi

    sudo -u "cvdoc" bash -c "source /home/ws/.script/envinit.bash && screen -dmS nav bash -c '/home/ws/.script/start'"

    sleep 0.1
    
    if is_running; then
        echo "Successfully started NAV daemon."
    else
        echo "Error: Failed to start NAV daemon."
        exit 1
    fi
}

attach() {
    sudo -u "cvdoc" bash -c "screen -r nav"
}

stop() {
    if is_running; then
        sudo -u "cvdoc" bash -c "screen -S nav -X quit"
        echo "Successfully stopped NAV daemon."
    fi
}

is_running() {
    sudo -u "cvdoc" bash -c "screen -wipe" >/dev/null 2>&1 || true

    if ls '/run/screen/S-cvdoc' 2>/dev/null | grep -q '.*\.nav'; then
        return 0
    else
        return 1
    fi
}

case "$1" in
    start)
        start
        ;;
    attach)
        attach
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo 'Usage: service nav {start|attach|stop|restart}'
        exit 1
        ;;
esac

exit 0