#!/bin/bash
source /home/ws/.script/envinit.bash

USE_FOXGLOVE="False"
USE_RVIZ="True"
USE_COMPOSITION="True"
NAV_MODE_FILE="/tmp/nav_mode"
WORLD_NAME="plan_b"

export DISPLAY=:0
export ROS_DOMAIN_ID=12

ros2 bag record -a -o /home/ws/bagdump/$(date +"%Y%m%d-%H%M%S") &
BAG_PID=$!
trap "kill $BAG_PID" EXIT

if [ ! -f "$NAV_MODE_FILE" ]; then
    ros2 launch pb2025_nav_bringup rm_navigation_reality_launch.py \
            world:=$WORLD_NAME \
            slam:=False \
            enable_planb:=True \
            use_robot_state_pub:=True \
            use_composition:=$USE_COMPOSITION \
            use_rviz:=$USE_RVIZ \
            use_foxglove:=$USE_FOXGLOVE
elif [ -f "$NAV_MODE_FILE" ]; then
    MODE=$(cat "$NAV_MODE_FILE")
    
    if [ "$MODE" = "SLAM" ]; then
        python3 /home/ws/.script/mapsaver.py &
        MAPSAVER_PID=$!
        trap "kill $MAPSAVER_PID" EXIT

        ros2 launch pb2025_nav_bringup \
            rm_navigation_reality_launch.py \
            slam:=True \
            use_robot_state_pub:=True \
            use_composition:=$USE_COMPOSITION \
            use_rviz:=$USE_RVIZ \
            use_foxglove:=$USE_FOXGLOVE
    elif [ "$MODE" = "LOCA" ]; then
        ros2 launch pb2025_nav_bringup rm_navigation_reality_launch.py \
            world:=$WORLD_NAME \
            slam:=False \
            use_robot_state_pub:=True \
            enable_planb:=True \
            use_composition:=$USE_COMPOSITION \
            use_rviz:=$USE_RVIZ \
            use_foxglove:=$USE_FOXGLOVE
    else
        ros2 launch pb2025_nav_bringup rm_navigation_reality_launch.py \
            world:=$WORLD_NAME \
            slam:=False \
            use_robot_state_pub:=True \
            enable_planb:=True \
            use_composition:=$USE_COMPOSITION \
            use_rviz:=$USE_RVIZ \
            use_foxglove:=$USE_FOXGLOVE
    fi
fi